//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaShack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.orderingredients = new HashSet<orderingredient>();
        }
    
        public int orderid { get; set; }
        public string name { get; set; }
        public string phonenumber { get; set; }
        public System.DateTime pickupdatetime { get; set; }
        public Nullable<System.DateTime> startdatetime { get; set; }
        public Nullable<System.DateTime> enddatetime { get; set; }
        public int statustypeid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderingredient> orderingredients { get; set; }
        public virtual statustype statustype { get; set; }
    }
}
